server:
  port: 8666

eureka:
  instance:
    hostname: ${DISCOVERY_SERVICE_DOMAIN:localhost}
  server:
     enableSelfPreservation: true
     a-s-g-query-timeout-ms: 300
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      # defaultZone: http://${eureka.instance.hostname:localhost}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port}/eureka/
