server:
  port: 8761

eureka:
  instance:
    hostname: ${DISCOVERY_HOSTNAME:localhost}
  server:
     enableSelfPreservation: true
     a-s-g-query-timeout-ms: 300
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port}/eureka/
